ShopClient/ShopClient/ShopClient_MVC/Controllers/ShopMangerController.cs
using IBatisNet.DataMapper;
using ShopClient_MVC.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopClient_MVC.Controllers
{
    public partial class ShopMangerController : Controller
    {
        private static ISqlMapper mapper = MappingData.GetInstance.MapperData;
        // GET: ShopManger
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddNewItem()
        {
            return View();
        }

        // GET: ShopManger/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ShopManger/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ShopManger/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ShopManger/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ShopManger/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ShopManger/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ShopManger/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        [HttpPost]
        public ActionResult UploadFiles(HttpPostedFileBase file, ItemUpload itemUp)
        {
            try
            {
                Item _item = itemUp.ItemFlow;
                _item.Name = _item.Name.Trim();
                if (!string.IsNullOrEmpty(_item.Name))
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        // setting for image fextension in web.config please search key AllowedImageExtensions
                        var allowedExtensionsStr = ConfigurationManager.AppSettings["AllowedImageExtensions"];
                        var ext = Path.GetExtension(file.FileName).ToLower(); //getting the extension(ex-.jpg)  

                        if (!string.IsNullOrWhiteSpace(allowedExtensionsStr)) //check what type of extension  
                        {
                            allowedExtensionsStr = allowedExtensionsStr.ToLower();
                            if (allowedExtensionsStr.Trim().Split(',').Contains(ext))
                            {
                                // convert inmage to byte buffer
                                _item.ImagePath = new byte[file.ContentLength];
                                file.InputStream.Read(_item.ImagePath, 0, file.ContentLength);
                            }
                            else
                            {
                                ViewBag.AddItemStatus = "<span style='color:red'>Chọn file với định dạng hình ảnh hoặc để trống</span>";
                                return View("AddNewItem");
                            }
                        }
                    }
                    mapper.Insert("AddNewItemEntity", _item);
                    ViewBag.AddItemStatus = "Đã thêm mới một mặt hàng thành công";
                }
                else
                {
                    ViewBag.AddItemStatus = "<span style='color:red'>[ERR]: Tên sản phẩm trống</span>";
                }
            }
            catch (Exception ex)
            {

                ViewBag.AddItemStatus = $"<span style='color:red'>Không thể thêm mới mặt hàng [ERR]: {ex.Message}</span>";
            }
            return View("AddNewItem");
        }
    }
}

ShopClient/ShopClient/ShopClient_MVC/Views/ShopManger/AddNewItem.cshtml
@using ShopClient_MVC.Models
@model ItemUpload
@{
    ViewBag.Title = "AddNewItem";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <br />
    @using (Html.BeginForm("UploadFiles", "ShopManger", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">

            <div class="form-group">
                <label for="Name" class="control-label col-md-2">Tên sản phẩm</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.ItemFlow.Name,
                    new
                    {
                        @class = "form-control",
                        placeholder = "tên sản phẩm",
                        required = "",
                        autofocus = ""
                    })
                </div>
            </div>

            <div class="form-group">
                <label for="Price" class="control-label col-md-2">Giá Sản Phẩm</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.ItemFlow.Price,
                    new
                    {
                        @class = "form-control",
                    })
                </div>
            </div>


            <div class="form-group">
                <label for="Discount" class="control-label col-md-2">Giảm giá (%)</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.ItemFlow.Discount,
                    new
                    {
                        @class = "form-control",
                    })
                </div>
            </div>
            <div class="form-group">
                <label for="AvailbleAmount" class="control-label col-md-2">Số lượng hiện có</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.ItemFlow.AvailbleAmount,
                    new
                    {
                        @class = "form-control",
                    })
                </div>
            </div>

            <div class="form-group">
                <label for="Description" class="control-label col-md-2">Mô tả về sản phẩm</label>
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.ItemFlow.Description,
                    new
                    {
                        @class = "form-control",
                    })
                </div>
            </div>


            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @*@Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <label for="Name" class="control-label col-md-2">Hình ảnh sản phẩm</label>
                <div class="col-md-10">

                    @Html.EditorFor(model => model.File, new { htmlAttributes = new { @class = "form-control", @type = "file", onchange = "show(this)" } })
                    @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
                </div>



            </div>
            <div class="form-group">
                <label class="control-label col-md-2">&nbsp;</label>
                <div class="col-md-10">
                    <img id="InputImge" height="100" width="100" style="border:thin" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm mới" class="btn btn-primary" />
                </div>
            </div>
            <hr />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10 text-success">
                    <label id="lbInform">
                        @(new HtmlString(ViewBag.AddItemStatus))
                    </label>
                </div>
            </div>
        </div>
    }
</div>
<script>
    function show(input) {
        if (input.files && input.files[0]) {
            var filerdr = new FileReader();
            filerdr.onload = function (e) {
                $('#InputImge').attr('src', e.target.result);
            }
            filerdr.readAsDataURL(input.files[0]);
        }
    }

    //window.onload = function () {
    //    if ($('#lbInform').length > 0 && $('#hdInform').length > 0)
    //        //$('#lbInform')
    //    document.getElementById('lbInform').innerHTML = $('#hdInform').val();
    //}
</script>