ShopClient/ShopClient/ShopClient_MVC/Controllers/DetailController.cs
using IBatisNet.DataMapper;
using ShopClient_MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;

namespace ShopClient_MVC.Controllers
{
    public class DetailController : Controller
    {
        private static ISqlMapper mapper = MappingData.GetInstance.MapperData;
        // GET: Detail
        public ActionResult Index()
        {
            var item = new Item();
            try
            {
                //get current Url
                string Uri = HttpContext.Request.Url.AbsoluteUri;
                var urlComponent = Uri.Split('/');
                string detailStr = urlComponent.Where(x => x.Contains("Item")).FirstOrDefault();
                int indexSub = detailStr.IndexOf('=');
                int id = Int32.Parse(detailStr.Substring(indexSub + 1, detailStr.Length - (indexSub + 1)));

                item = GetAllItemEntity().Where(x => x.ID == id).FirstOrDefault();
            }
            catch (Exception ex)
            {
            }
            if (item == null) item = new Item();
            return View(item);
        }
        
        private static IList<Item> GetAllItemEntity()
        {
            try
            {
                return mapper.QueryForList<Item>("GetAllItemEntity",null);
            }
            catch (Exception ex)
            {
            return new List<Item>();
                //throw ex;
            }
        }
    }
}

ShopClient/ShopClient/ShopClient_MVC/Controllers/HomeController.cs
using IBatisNet.DataMapper;
using ShopClient_MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopClient_MVC.Controllers
{
    public class HomeController : Controller
    {
        private static ISqlMapper mapper = MappingData.GetInstance.MapperData;
        public ActionResult Index()
        {
            var itemList = GetAllItemEntity();
            return View(itemList);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        private static IList<Item> GetAllItemEntity()
        {
            try
            {
                return mapper.QueryForList<Item>("GetAllItemEntity", null);
            }
            catch (Exception ex)
            {
                return new List<Item>();
                //throw ex;
            }
        }

        [HttpPost]
        public ActionResult AjaxCheckLogin(string userName, string password)
        {
            string resultStr = "Login Fail";
            try
            {
                IDictionary<string, object> parameters = new Dictionary<string, object>();
                parameters.Add("USER_NAME", userName);
                parameters.Add("PASSWORD", password);

                var user = mapper.QueryForObject<User>("FindUserEntity", parameters);
                if (user != null)
                {
                    resultStr = "Success";
                }
            }
            catch (Exception ex)
            { 
            }
             return Json(resultStr);
        }
    }
}

ShopClient/ShopClient/ShopClient_MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ShopClient/ShopClient/ShopClient_MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ShopClient/ShopClient/ShopClient_MVC/Views/Home/Index.cshtml
@using ShopClient_MVC.Models
@{
    ViewBag.Title = "Home Page";
}
@model IEnumerable<Item>

@Styles.Render("~/Css/Home.css")
<!-- Page Content -->
<br />
<hr />
<div class="container">
    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Shop Name</h1>
            <div class="list-group">
                <a href="#" class="list-group-item">Phân loại 1</a>
                <a href="#" class="list-group-item">Phân loại 2</a>
                <a href="#" class="list-group-item">Phân loại 3</a>
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">
            <div class="row">
                @{
                    foreach (var item in Model)
                    {
                        string sale = "₫" + item.Price.ToString();
                        if (item.Price == 0)
                        {
                            sale = "<Strong>LIÊN HỆ</strong>";
                        }
                        else
                        if (item.Discount > 0)
                        {
                            var realSale = item.Price - item.Price * item.Discount / 100;
                            sale = $"<span>₫<strong>{realSale.ToString()}</strong> <s style='color:red'>{item.Price.ToString()}</s></span>";
                        }

                        <div class="col-sm-6 col-md-4">
                            <div class="thumbnail">
                                @{
                                    if (item.ImagePath != null)
                                    {
                                        var base64 = Convert.ToBase64String((item.ImagePath));
                                        var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                                        <img src='@imgsrc' alt="NO IMAGE" class="imageThumbnails">
                                    }
                                    else
                                    {
                                        <img src='' class="imageThumbnails" alt="NO IMAGE">
                                    }
                                }
                                <div class="caption">
                                    <div class="caption">
                                        @{
                                            IDictionary<string, object> routeValues = new Dictionary<string, object>();
                                            routeValues.Add("Item", item.ID);

                                            <h4>@Html.ActionLink(item.Name, "Index", "Detail", new RouteValueDictionary(routeValues), null)</h4>

                                            <h5>@(new HtmlString(sale))</h5>

                                            //    min-height:130px; max-height:130px; overflow:hidden;
                                            //get 100 letter to show
                                            if (!string.IsNullOrWhiteSpace(item.Description))
                                            {
                                                int strLength = item.Description.Trim().Length;
                                                strLength = strLength < 100 ? strLength : 100;

                                                var descript = item.Description.Trim().Substring(0, strLength);
                                                descript = descript + "...";
                                                <p class="descriptionThumbnails">@descript</p>
                                            }
                                            else
                                            {
                                                <p class="descriptionThumbnails">...</p>
                                            }
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }

            </div>
            <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->
</div>
<!-- /.container -->